<?php
// module/Familia/view/familia/familia/delete.phtml:

$title = 'Delete familia';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($familia->codigo); ?>' by
    '<?php echo $this->escapeHtml($familia->descricao); ?>'?
</p>
<?php
$url = $this->url('familia', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $familia->id; ?>" />
    <input type="submit" name="del" value="Yes" />
    <input type="submit" name="del" value="No" />
</div>
</form>