<?php
// module/Album/view/album/album/index.phtml:

$title = 'Familia';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url(null, array('controller'=>'familia','action'=> 'cadastro'));?>" class='btn btn-primary pull-right'>Novo Registro</a>
</p>

<table class="table"  style="margin-top: 50px;">
<tr>
    <th>Código</th>
    <th>Descrição</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($familias as $familia) : ?>
<tr>
    <td><?php echo $this->escapeHtml($familia->codigo);?></td>
    <td><?php echo $this->escapeHtml($familia->descricao);?></td>
    <td>
        <a href="<?php echo $this->url(null, array('controller'=>'familia','action'=> 'cadastro','id' => $this->escapeHtml($familia->familia)));?>">Edit</a>
        <a href="<?php echo $this->url(null, array('controller'=>'familia','action'=> 'delete','id' => $this->escapeHtml($familia->familia)));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>