<?php
// module/Familia/view/linha/linha/delete.phtml:

$title = 'Delete linha';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($linha->codigo_linha); ?>' by
    '<?php echo $this->escapeHtml($linha->nome); ?>'?
</p>
<?php
$url = $this->url(null, array(
    'controller' => 'linha',
    'action' => 'delete',
    'id' => $this->id,
        )
);
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="linha" value="<?php echo (int) $linha->linha; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>