<?php
// module/Familia/view/fabrica/fabrica/delete.phtml:

$title = 'Delete fabrica';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($fabrica->codigo_fabrica); ?>' by
    '<?php echo $this->escapeHtml($fabrica->nome); ?>'?
</p>
<?php
$url = $this->url(null, array(
    'controller' => 'fabrica',
    'action' => 'delete',
    'id' => $this->id,
        )
);
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="fabrica" value="<?php echo (int) $fabrica->fabrica; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>